### PR TITLE
RAINCATCH-1108jstaffor Datasync cloud and client

### PR DESCRIPTION
**Pull request by jstaffor**
RAINCATCH-1108jstaffor + updates made to original RAINCATCH-1108

### CODE REVIEW

**Comment by jstaffor** [comment]
@austincunningham - no review required atm. I need feedback from W before I remove the WIP, and for a review to take place. (terminology update ok'd  by W[1])

[1] "#47"

**Review by austincunningham — COMMENTED** [review]
The data sync data looks good but seems to be a lot of extra file changes that are not related to the original PR seem to be related to the security module.

**Review by witmicko — CHANGES_REQUESTED** [review]
same comment as @austincunningham, can you rebase on master all unrelated files?

**Comment by jstaffor** [comment]
W ok with my update[1] re Client and Cloud App, and so, happy to mark as doc-approved

[1] "https://github.com/feedhenry-raincatcher/raincatcher-docs/pull/47"

**Comment by jstaffor** [comment]
Closing this in favor of #41 . I've added _only_ my changes to 41. Hopefully, this will make it easier to see my changes.

**Pull request closed without merging**
