### PR TITLE
Rhmap 17460 - Review the api docs for the wfm

### PR DESCRIPTION
**Pull request by jstaffor**
(1)auth-passport, (2) datasync-client and (3) wfm/docs reviewed (at a high level)

### CODE REVIEW

**Review by austincunningham — COMMENTED** [review]
As these html files are auto generated from the comments in the code base by typedoc, its the comments that need updating . :)

**Comment by wtrocki** [comment]
@austincunningham - Let's port this changes (if accepted to core repository).

**Comment by wtrocki** [comment]
@austincunningham - Let's port this changes (if accepted to core repository) or create ticket for this work.

**Comment by jstaffor** [comment]
@austincunningham  - as the changes will be ported back (as per W's comments), and this PR can then be closed - just ignore the .adoc files in this PR. I don't know why they were added when I pushed as I didn't commit them...i've still a bit to learn about git :(

**Review by austincunningham — COMMENTED** [review]
change ported in the following pr https://github.com/feedhenry-raincatcher/raincatcher-core/pull/124

**Pull request closed without merging**
